excluded:
  - Meowtastic/Circles Of Hell
  - MeshtasticProtobufs
  - protobufs
  - scripts

disabled_rules:
  - empty_count # temporarily
  - line_length # temporarily
  - closure_parameter_position
  - indentation_width
  - function_body_length
  - inclusive_language
  - trailing_comma
  - nesting
  - type_body_length  
  - todo
  - opening_brace
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - file_name
  - file_name_no_space
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_subject
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - switch_case_on_newline
  - toggle_bool
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - yoda_condition

identifier_name:
  min_length: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - S
    - M
    - L
    - XL
line_length:
  ignores_comments: true
  warning: 120
  error: 150
statement_position:
  statement_mode: uncuddled_else
multiline_arguments:
  first_argument_location: next_line