//
//  Generator.swift
//  protoc-gen-configform-swift
//
//  Copyright(c) Garth Vander Houwen 9/18/26.
//
//  Emits Meshtastic/Model/ConfigForms/ConfigFormSchema.swift: for every message nested
//  under meshtastic.Config and meshtastic.ModuleConfig, a typed descriptor per field
//  with its tag, proto name, kind and a WritableKeyPath into the generated message.
//
//  The key path is the point. A form that reads and writes fields by number needs
//  either runtime reflection or a generated table, and swift-protobuf gives forms
//  nothing usable at runtime: `traverse` skips fields at their default value and the
//  name map is internal. So the table is generated here, and because it is Swift, a
//  field the schema renames or removes fails to compile instead of failing to render.
//
//  Property names come from SwiftProtobufNamer - the same naming engine protoc-gen-swift
//  uses - so `sx126x_rx_boosted_gain` becomes `sx126XRxBoostedGain` here exactly as it
//  did there. Nothing in this plugin reads the field_metadata custom option; labels,
//  descriptions and units are looked up at runtime through FieldMetadataRegistry by
//  message name and tag, which is the one key stable by contract.
//

import Foundation
import SwiftProtobuf
import SwiftProtobufPluginLibrary

struct GenError: Error, CustomStringConvertible {
    let description: String
}

@main
struct ConfigFormSwiftGenerator: CodeGenerator {

    var supportedFeatures: [Google_Protobuf_Compiler_CodeGeneratorResponse.Feature] {
        [.proto3Optional]
    }

    var version: String? { "1.0.0" }

    /// The two messages whose nested messages are configuration screens.
    static let roots: Set<String> = ["meshtastic.Config", "meshtastic.ModuleConfig"]

    struct Field {
        let tag: Int32
        let name: String            // proto name; dotted when flattened from a nested message
        let swiftType: String       // value type for the ConfigField generic
        let keyPath: String         // "\\.mapReportSettings.positionPrecision"
        let accessor: String        // Swift identifier for the static, e.g. mapReportSettings_positionPrecision
        let kind: String            // ConfigFieldKind case name
        let identityMessage: String // proto name of the message the tag belongs to
        let enumTypeName: String?   // proto name of the enum, for registry lookups of option labels
        let deprecated: Bool
        let unsupportedReason: String?
    }

    func generate(
        files: [FileDescriptor],
        parameter: any CodeGeneratorParameter,
        protoCompilerContext: any ProtoCompilerContext,
        generatorOutputs: any GeneratorOutputs
    ) throws {
        let namer = SwiftProtobufNamer()
        var blocks: [(protoName: String, swiftName: String, text: String)] = []

        for file in files {
            for root in file.messages where Self.roots.contains(root.fullName) {
                var stack = root.messages
                while !stack.isEmpty {
                    let message = stack.removeFirst()
                    stack.append(contentsOf: message.messages)
                    let fields = try collect(message, namer: namer, prefixPath: "", prefixName: "", depth: 0)
                    blocks.append((message.fullName, namer.fullName(message: message),
                                   render(message: message, swiftName: namer.fullName(message: message), fields: fields)))
                }
            }
        }
        guard !blocks.isEmpty else {
            throw GenError(description: "no messages under meshtastic.Config or meshtastic.ModuleConfig were found - pass config.proto and module_config.proto")
        }
        blocks.sort { $0.protoName < $1.protoName }

        var out = """
        // DO NOT EDIT -- generated by scripts/protoc-gen-configform-swift from config.proto and module_config.proto.
        //
        // One typed descriptor per field of every configuration message: its tag, proto
        // name, kind and a key path into the generated message. Labels, descriptions and
        // units are not here; they are read at runtime from FieldMetadataRegistry by
        // message name and tag.

        import Foundation
        import MeshtasticProtobufs


        """
        for block in blocks {
            out += block.text + "\n"
        }
        out += "enum ConfigFormSchema {\n"
        out += "\t/// Every configuration message, for the completeness test and any walk over all of them.\n"
        out += "\tstatic let all: [ConfigMessageDescriptor] = [\n"
        for block in blocks {
            out += "\t\t.init(protoName: \(block.swiftName).protoName, fields: \(block.swiftName).fieldSummaries),\n"
        }
        out += "\t]\n}\n"
        try generatorOutputs.add(fileName: "ConfigFormSchema.swift", contents: out)
    }

    /// Descriptors for a message's fields, flattening singular message-typed fields one
    /// level (`map_report_settings.position_precision`) so a form can bind to them
    /// directly. Deeper nesting is left as a `.message` descriptor.
    private func collect(_ message: Descriptor, namer: SwiftProtobufNamer,
                         prefixPath: String, prefixName: String, depth: Int) throws -> [Field] {
        var result: [Field] = []
        for field in message.fields {
            let names = namer.messagePropertyNames(field: field, prefixed: "", includeHasAndClear: false)
            let property = names.name
            let keyPath = prefixPath + "." + property
            let protoName = prefixName.isEmpty ? field.name : prefixName + "." + field.name
            let accessor = prefixName.isEmpty ? property : prefixName.split(separator: ".").map(String.init).map { pieceName($0, namer: namer, in: message) }.joined(separator: "_") + "_" + property

            if field.isMap || field.isRepeated {
                result.append(Field(tag: field.number, name: protoName, swiftType: "", keyPath: keyPath, accessor: accessor,
                                    kind: "repeated", identityMessage: message.fullName, enumTypeName: nil,
                                    deprecated: field.options.deprecated,
                                    unsupportedReason: field.isMap ? "map field" : "repeated field"))
                continue
            }
            if field.realContainingOneof != nil {
                result.append(Field(tag: field.number, name: protoName, swiftType: "", keyPath: keyPath, accessor: accessor,
                                    kind: "oneof", identityMessage: message.fullName, enumTypeName: nil,
                                    deprecated: field.options.deprecated, unsupportedReason: "member of a oneof"))
                continue
            }
            switch field.type {
            case .message:
                let sub = field.messageType!
                if depth == 0 {
                    // Flatten one level; the child's own descriptor is emitted too so a
                    // caller that wants the whole sub-message can have it.
                    result.append(Field(tag: field.number, name: protoName, swiftType: namer.fullName(message: sub),
                                        keyPath: keyPath, accessor: accessor, kind: "message",
                                        identityMessage: message.fullName, enumTypeName: nil,
                                        deprecated: field.options.deprecated, unsupportedReason: nil))
                    result += try collect(sub, namer: namer, prefixPath: keyPath, prefixName: protoName, depth: depth + 1)
                } else {
                    result.append(Field(tag: field.number, name: protoName, swiftType: namer.fullName(message: sub),
                                        keyPath: keyPath, accessor: accessor, kind: "message",
                                        identityMessage: message.fullName, enumTypeName: nil,
                                        deprecated: field.options.deprecated, unsupportedReason: nil))
                }
            case .enum:
                let e = field.enumType!
                result.append(Field(tag: field.number, name: protoName, swiftType: namer.fullName(enum: e),
                                    keyPath: keyPath, accessor: accessor, kind: "enumeration",
                                    identityMessage: message.fullName, enumTypeName: e.fullName,
                                    deprecated: field.options.deprecated, unsupportedReason: nil))
            default:
                guard let (swiftType, kind) = scalar(field.type) else {
                    throw GenError(description: "\(message.fullName).\(field.name): unsupported field type \(field.type)")
                }
                result.append(Field(tag: field.number, name: protoName, swiftType: swiftType, keyPath: keyPath,
                                    accessor: accessor, kind: kind, identityMessage: message.fullName,
                                    enumTypeName: nil, deprecated: field.options.deprecated, unsupportedReason: nil))
            }
        }
        return result
    }

    /// The Swift property name for one dotted piece of a flattened path.
    private func pieceName(_ protoFieldName: String, namer: SwiftProtobufNamer, in message: Descriptor) -> String {
        if let f = message.fields.first(where: { $0.name == protoFieldName }) {
            return namer.messagePropertyNames(field: f, prefixed: "", includeHasAndClear: false).name
        }
        return NamingUtils.toLowerCamelCase(protoFieldName)
    }

    private func scalar(_ type: Google_Protobuf_FieldDescriptorProto.TypeEnum) -> (String, String)? {
        switch type {
        case .bool: return ("Bool", "bool")
        case .int32, .sint32, .sfixed32: return ("Int32", "int32")
        case .uint32, .fixed32: return ("UInt32", "uint32")
        case .int64, .sint64, .sfixed64: return ("Int64", "int64")
        case .uint64, .fixed64: return ("UInt64", "uint64")
        case .float: return ("Float", "float")
        case .double: return ("Double", "double")
        case .string: return ("String", "string")
        case .bytes: return ("Data", "bytes")
        default: return nil
        }
    }

    private func render(message: Descriptor, swiftName: String, fields: [Field]) -> String {
        var s = "extension \(swiftName): ConfigSchemaMessage {\n"
        s += "\tstatic let protoName = \"\(message.fullName)\"\n\n"
        s += "\tenum Fields {\n"
        for f in fields where f.unsupportedReason == nil {
            s += "\t\tstatic let \(f.accessor) = ConfigField<\(swiftName), \(f.swiftType)>("
            s += "tag: \(f.tag), name: \"\(f.name)\", keyPath: \\\(f.keyPath), "
            s += "identity: FieldIdentity(messageName: \"\(f.identityMessage)\", tag: \(f.tag)))\n"
        }
        s += "\t}\n\n"
        s += "\tstatic let allFields: [AnyConfigField<\(swiftName)>] = [\n"
        for f in fields {
            if let reason = f.unsupportedReason {
                s += "\t\t.unsupported(tag: \(f.tag), name: \"\(f.name)\", kind: .\(f.kind), "
                s += "identity: FieldIdentity(messageName: \"\(f.identityMessage)\", tag: \(f.tag)), "
                s += "reason: \"\(reason)\", isDeprecated: \(f.deprecated)),\n"
            } else {
                s += "\t\t.init(Fields.\(f.accessor), kind: .\(f.kind)"
                if let e = f.enumTypeName { s += ", enumTypeName: \"\(e)\"" }
                if f.deprecated { s += ", isDeprecated: true" }
                s += "),\n"
            }
        }
        s += "\t]\n}\n"
        return s
    }
}
