//
//  DocumentationSearch.swift
//  Meshtastic
//
//  Copyright(c) Garth Vander Houwen 9/13/26.
//
import Foundation
import OSLog

/// The in-app documentation, searchable from the same field as the settings.
///
/// A user searching "hops" may want to change the setting or to understand what a
/// hop is. Both answers are in the app, so both are offered — settings first, then
/// documentation under its own heading.
///
/// Nothing here is hand-maintained: `docs/index.json` is generated by
/// `scripts/build-docs.sh` from the pages themselves, so it cannot describe a page
/// that is not there.
enum DocumentationSearch {

	struct Page: Identifiable, Hashable {
		let id: String
		let title: String
		/// "user" or "developer".
		let section: String
		let keywords: [String]
	}

	/// Not `static let`: the translated index arrives asynchronously from the CDN,
	/// so a value cached at first use would pin whatever was available then.
	///
	/// Main-actor isolated because `DocBundle` is, and the translated index is read
	/// from it. Search runs from the view anyway.
	@MainActor
	static var pages: [Page] { load() }

	/// Pages matching `query`, best first.
	///
	/// Documentation is never de-emphasised: a page reads the same whether or not a
	/// radio is connected, so the reasons that dim a settings result do not apply.
	@MainActor
	static func search(_ query: String) -> [Page] {
		rank(query, in: pages)
	}

	/// The ranking half, over an explicit page list, so it can be tested without
	/// depending on what the bundle happens to contain.
	static func rank(_ query: String, in pages: [Page]) -> [Page] {
		let trimmed = query.trimmingCharacters(in: .whitespacesAndNewlines)
		guard trimmed.count >= SettingsSearchEngine.minimumQueryLength else { return [] }

		return pages
			.compactMap { page -> (Page, Int)? in
				var score = 0
				if page.title.localizedStandardCompare(trimmed) == .orderedSame {
					score += 1000
				} else if page.title.localizedStandardContains(trimmed) {
					score += 250
				}
				if page.keywords.contains(where: { $0.localizedStandardContains(trimmed) }) {
					score += 100
				}
				return score > 0 ? (page, score) : nil
			}
			// Ties break by title, so the order never depends on how the file was read.
			.sorted { $0.1 != $1.1 ? $0.1 > $1.1 : $0.0.title < $1.0.title }
			.map(\.0)
	}

	@MainActor
	private static func load() -> [Page] {
		// Prefer the translated index the documentation browser uses. Without this a
		// localized query finds a page inside the browser and nothing from Settings
		// search, which reads as search being broken rather than untranslated.
		let language = Bundle.main.documentationLanguageCode
		if language != "en",
		   let translated = DocBundle.shared.searchIndex(for: language), !translated.isEmpty {
			return translated.map {
				Page(id: $0.id, title: $0.title, section: $0.section, keywords: $0.keywords)
			}
		}

		guard let url = Bundle.main.url(forResource: "index", withExtension: "json",
										subdirectory: "docs"),
			  let data = try? Data(contentsOf: url) else {
			Logger.services.warning("docs/index.json not found; documentation search will be empty")
			return []
		}
		struct Entry: Decodable {
			let id: String
			let title: String
			let section: String
			let keywords: [String]
		}
		guard let entries = try? JSONDecoder().decode([Entry].self, from: data) else {
			Logger.services.error("docs/index.json could not be decoded")
			return []
		}
		return entries.map { Page(id: $0.id, title: $0.title, section: $0.section, keywords: $0.keywords) }
	}
}
